[package]
name = "plc_rowan_parser"
version = "0.1.0"
description = "The Rust parser for rust-analyzer."
rust-version = "1.91"


edition = "2024"


[dependencies]
drop_bomb = "0.1.5"
logos = "0.12.0"
rusty = { path = "../.." }

[dev-dependencies]
insta.workspace = true

