[package]
name = "plc_rowan_syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
rowan = "0.15"
logos = "0.12.0"
plc_rowan_parser = { path = "../plc_rowan_parser" }
text-size = "1.1.1"
either = "1.15.0"
