[alias]
xtask = "run --package xtask --"
benchmark = "run --package xtask --"
benchmark-sql = "run --package xtask --features=sql -- --reporter=sql"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-fuse-ld=lld","-C", "link-arg=--target=aarch64-linux-gnu"]
linker = "clang"

[target.x86_64-pc-windows-msvc]
linker = "lld-link"
#rustflags = ["-C", "link-arg=-fuse-ld=lld-link","-C", "link-arg=--target=aarch64-linux-gnu"]