[package]
name = "plc_lowering"
version = "0.1.0"
edition = "2021"

[dependencies]
plc = { path = "../..", package = "rusty" }
plc_ast = { path = "../plc_ast" }
plc_source = { path = "../plc_source" }
plc_diagnostics = { path = "../plc_diagnostics" }
log.workspace = true

[dev-dependencies]
plc_driver = { path = "../plc_driver" }
insta = "1.31.0"
