name: Build Windows

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Windows Build
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.90.0

      - name: Install LLVM
        shell: pwsh
        run: |
          $llvmUrl = "https://github.com/PLC-lang/llvm-package-windows/releases/download/v21.1.7/LLVM-21.1.7-win64.7z"
          $llvmArchive = "LLVM-21.1.7-win64.7z"
          Invoke-WebRequest -Uri $llvmUrl -OutFile $llvmArchive
          7z x $llvmArchive -o"./llvm" -y
          $llvmBin = (Resolve-Path "./llvm/bin").Path
          echo "$llvmBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Cargo test (Unit)
        run: cargo test --lib -- --nocapture

      - name: Cargo test (Correctness)
        run: cargo test correctness -- --nocapture --test-threads=1

      - name: Cargo test (Integration)
        run: cargo test integration -- --nocapture --test-threads=1

      - name: Release Build
        run: cargo build --release --workspace

      - uses: actions/upload-artifact@master
        with:
          name: plc.exe
          path: target/release/plc.exe

      - uses: actions/upload-artifact@master
        with:
          name: stdlib.dll
          path: target/release/iec61131std.dll

      - uses: actions/upload-artifact@master
        with:
          name: stdlib.lib
          path: target/release/iec61131std.lib
